services:
    postgres:
        image: 'postgres'
        container_name: db_postgres
        restart: 'always'
        environment:
            POSTGRES_PASSWORD: 'admin'
            POSTGRES_DB: 'coloncafebar'
        volumes:
          - database-data:/var/lib/postgresql/data/
    backend:
        image: 'silvafacundo/sip2021-coloncafebar'
        restart: 'always'
        ports:
            - '80:3000'
        environment:
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_DB: coloncafebar
            DATABASE_USER: postgres
            DATABASE_PASSWORD: admin
            MAPS_APIKEY:
            MP_TOKEN:
            NODE_ENV: production
            FIREBASE_PID:
            FIREBASE_PKID:
            FIREBASE_PK:
            FIREBASE_EMAIL:
            FIREBASE_CID:
            FIREBASE_AUTHCERT:
            FIREBASE_CLIENTCERT:
            EMAIL_HOST:
            EMAIL_PORT:
            EMAIL_USER:
            EMAIL_PASS:
            FRONT_URL: https://backend-silvafacundo.cloud.okteto.net
            BACK_URL: https://backend-silvafacundo.cloud.okteto.net/api
volumes:
  database-data: