services:
    postgres:
        image: 'postgres'
        container_name: db_postgres
        restart: 'always'
        environment:
            POSTGRES_PASSWORD:
            POSTGRES_DB: 'coloncafebar'
        volumes:
          - database-data:/var/lib/postgresql/data/
    backend:
        image: 'silvafacundo/sip2021-coloncafebar'
        restart: 'always'
        ports:
            - '80:3000'
        environment:
            DATABASE_HOST: postgres
            DATABASE_PORT: 5432
            DATABASE_DB: coloncafebar
            DATABASE_USER:
            DATABASE_PASSWORD:
            MP_TOKEN:
            NODE_ENV: production
            FIREBASE_PID:
            FIREBASE_PKID:
            FIREBASE_PK:
            FIREBASE_EMAIL:
            FIREBASE_CID:
            FIREBASE_AUTHCERT:
            FIREBASE_CLIENTCERT:
            MAPS_APIKEY:
volumes:
  database-data: